<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.6" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.6" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.6" />
    <PackageReference Include="Avalonia.Skia" Version="11.3.6" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.6" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1" />
    <PackageReference Include="SharpHook" Version="5.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="DockableControl.axaml.cs">
      <DependentUpon>DockableControl.axaml</DependentUpon>
    </Compile>
    <Compile Update="DockableControl.axaml.cs">
      <DependentUpon>DockableControl.axaml</DependentUpon>
    </Compile>
    <Compile Update="DefaultDockableControl.axaml.cs">
      <DependentUpon>DefaultDockableControl.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
